### ISSUE TITLE
Prometheus Bundle causing a Memory Leak.

### ISSUE THREAD

**Issue by vikaspalkar** [TIBCOSoftware/bw-tooling#11]
Integrating Prometheus bundle with BWCE app causing a Memory leak. The BWCE pod/container not releasing memory and also not destroying a pod in case there is an OOM issue. You can check the below heap dump analysis screenshot :

![image (14)](https://user-images.githubusercontent.com/12160289/83253000-dad34a00-a1c9-11ea-972e-9a8fa9311ccd.png)

**Comment by ntrip** [comment]
While starting the Prometheus you can set below flags to configuring the local storage and avoid the OOM issue: 

--storage.tsdb.path: This determines where Prometheus writes its database. Defaults to data/.
--storage.tsdb.retention.time: This determines when to remove old data. Defaults to 15d. Overrides storage.tsdb.retention if this flag is set to anything other than the default.
--storage.tsdb.retention.size: [EXPERIMENTAL] This determines the maximum number of bytes that storage blocks can use (note that this does not include the WAL size, which can be substantial). The oldest data will be removed first. Defaults to 0 or disabled. This flag is experimental and can be changed in future releases. Units supported: KB, MB, GB, PB. Ex: "512MB"
--storage.tsdb.retention: This flag has been deprecated in favor of storage.tsdb.retention.time.
--storage.tsdb.wal-compression: This flag enables compression of the write-ahead log (WAL). Depending on your data, you can expect the WAL size to be halved with little extra CPU load. Note that if you enable this flag and subsequently downgrade Prometheus to a version below 2.11.0 you will need to delete your WAL as it will be unreadable.

For more details refer here: 
https://prometheus.io/docs/prometheus/latest/storage/

Let us know if you still face the issue.

**Comment by vikaspalkar** [comment]
Hi @ntrip, I work in TIBCO Support. One of our customer is facing this issue. Can you please discuss this with @awagle once he has more idea on this issue. Thanks

**Comment by awagle** [comment]
This is BW going out memory and not Prometheus. Reopening issue.

**Comment by skumar-tibco** [comment]
The issue has been resolved.
